spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${OAUTH_GITHUB_CLIENT_ID:clientId}
            clientSecret: ${OAUTH_GITHUB_CLIENT_SECRET:clientSecret}
  datasource:
    url: jdbc:h2:mem:${DB_NAME:db}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:password}
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings.web-allow-others: true
