spring:
  security:
    oauth2:
      defaultSuccessUrl: ${OAUTH_DEFAULT_SUCCESS_URL:http://localhost:3000}
      client:
        registration:
          github:
            clientId: ${OAUTH_GITHUB_CLIENT_ID:clientId}
            clientSecret: ${OAUTH_GITHUB_CLIENT_SECRET:clientSecret}
  datasource:
    url: jdbc:h2:mem:${DB_NAME:db}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:password}
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings.web-allow-others: true
app:
  auth:
    tokenSecret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
    tokenExpirationMsec: 864000000
  cors:
    allowedOrigins: http://localhost:3000,http://localhost:8080
  oauth2:
    defaultSuccessUrl: ${OAUTH_DEFAULT_SUCCESS_URL:http://localhost:3000}
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect
